create table if not exists customers (
    id bigint generated by default as identity primary key,
    customer_number varchar(50) not null unique,
    display_name varchar(200) not null,
    email varchar(320) not null unique,
    active boolean not null default true
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    code varchar(50) not null unique,
    name varchar(200) not null,
    coverage_limit numeric(19, 2) not null,
    premium numeric(19, 2) not null,
    active boolean not null default true
);

create table if not exists policies (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references customers(id),
    product_id bigint not null references products(id),
    valid_from date not null,
    valid_to date not null,
    coverage_limit numeric(19, 2) not null,
    premium numeric(19, 2) not null,
    status varchar(20) not null
);

create table if not exists claims (
    id bigint generated by default as identity primary key,
    customer_number varchar(50) not null,
    policy_id bigint,
    claim_type varchar(100) not null,
    description varchar(1000),
    amount numeric(12, 2) not null,
    status varchar(30) not null,
    created_at timestamp not null
);

create table if not exists payouts (
    id bigint generated by default as identity primary key,
    claim_id bigint not null unique,
    policy_id bigint not null,
    amount numeric(19, 2) not null,
    currency varchar(3) not null,
    status varchar(20) not null
);

create table if not exists invoices (
    id bigint generated by default as identity primary key,
    policy_id bigint not null unique,
    customer_id bigint not null,
    amount numeric(19, 2) not null,
    currency varchar(3) not null,
    status varchar(20) not null
);
